name: 部署 h5 应用
on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: 构建产物
        run: |
          npm install pnpm -g
          pnpm i
          pnpm build:h5

      - name: 生成404页面
        run: |
          cp dist/index.html dist/404.html

      - name: h5 部署
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
